#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any
from uuid import uuid4

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.skills import SkillRegistry
from skills_sdk.contract import SkillContext


def _load_json_arg(raw: str | None, *, field_name: str) -> dict[str, Any]:
    if not raw:
        return {}
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON for {field_name}: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"{field_name} must be a JSON object")
    return value


def _load_json_file(path: str | None, *, field_name: str) -> dict[str, Any]:
    if not path:
        return {}
    text = Path(path).read_text(encoding="utf-8")
    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON file for {field_name} ({path}): {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"{field_name} file must contain a JSON object")
    return value


def _skill_to_json(skill_record: Any) -> dict[str, Any]:
    spec = skill_record.spec
    return {
        "skill_id": spec.skill_id,
        "name": spec.name,
        "version": spec.version,
        "description": spec.description,
        "mode": spec.mode,
        "permissions": list(spec.permissions),
        "timeout_sec": spec.timeout_sec,
        "max_result_bytes": spec.max_result_bytes,
        "input_schema": spec.input_schema,
        "manifest": skill_record.manifest,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Run local model-callable skills from terminal.")
    parser.add_argument("--skills-dir", default="skills", help="Path to skills directory.")
    subparsers = parser.add_subparsers(dest="cmd", required=True)

    list_parser = subparsers.add_parser("list", help="List discovered skills")
    list_parser.add_argument("--skill-id", default=None, help="Optional exact skill id filter")

    exec_parser = subparsers.add_parser("exec", help="Execute one skill")
    exec_parser.add_argument("--skill-id", required=True, help="Skill id from skill.yaml")
    exec_parser.add_argument("--arguments-json", default=None, help="Inline JSON object for skill arguments.")
    exec_parser.add_argument("--arguments-file", default=None, help="Path to JSON file for skill arguments.")
    exec_parser.add_argument("--config-json", default=None, help="Inline JSON object for skill config.")
    exec_parser.add_argument("--config-file", default=None, help="Path to JSON file for skill config.")
    exec_parser.add_argument("--chat-id", type=int, default=-1)
    exec_parser.add_argument("--user-id", type=int, default=1)
    exec_parser.add_argument("--role-id", type=int, default=1)
    exec_parser.add_argument("--role-name", default="dev")
    exec_parser.add_argument("--chain-id", default=None, help="Optional chain id; autogenerated when omitted.")

    args = parser.parse_args()

    registry = SkillRegistry()
    registry.discover(args.skills_dir)

    if args.cmd == "list":
        records = []
        for spec in sorted(registry.list_specs(), key=lambda item: item.skill_id):
            if args.skill_id and spec.skill_id != str(args.skill_id):
                continue
            record = registry.get(spec.skill_id)
            if record is None:
                continue
            records.append(_skill_to_json(record))
        print(
            json.dumps(
                {
                    "skills_dir": str(Path(args.skills_dir)),
                    "count": len(records),
                    "skills": records,
                },
                ensure_ascii=False,
                indent=2,
                default=str,
            )
        )
        return 0

    skill_id = str(args.skill_id)
    record = registry.get(skill_id)
    if record is None:
        print(
            json.dumps(
                {
                    "error": f"Skill '{skill_id}' not found",
                    "available": [spec.skill_id for spec in sorted(registry.list_specs(), key=lambda item: item.skill_id)],
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return 2

    arguments = _load_json_file(args.arguments_file, field_name="arguments")
    arguments.update(_load_json_arg(args.arguments_json, field_name="arguments"))

    config = _load_json_file(args.config_file, field_name="config")
    config.update(_load_json_arg(args.config_json, field_name="config"))

    config_errors = record.instance.validate_config(config)
    if config_errors:
        print(json.dumps({"status": "invalid_config", "errors": config_errors}, ensure_ascii=False, indent=2))
        return 3

    ctx = SkillContext(
        chain_id=(str(args.chain_id).strip() if args.chain_id else uuid4().hex[:8]),
        chat_id=args.chat_id,
        user_id=args.user_id,
        role_id=args.role_id,
        role_name=args.role_name,
    )
    result = record.instance.run(ctx, arguments, config)
    print(
        json.dumps(
            {
                "skill": _skill_to_json(record),
                "arguments": arguments,
                "config": config,
                "context": {
                    "chain_id": ctx.chain_id,
                    "chat_id": ctx.chat_id,
                    "user_id": ctx.user_id,
                    "role_id": ctx.role_id,
                    "role_name": ctx.role_name,
                },
                "result": {
                    "ok": result.ok,
                    "output": result.output,
                    "error": result.error,
                    "metadata": result.metadata,
                },
            },
            ensure_ascii=False,
            indent=2,
            default=str,
        )
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ValueError as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False))
        raise SystemExit(1)
